orbs:
    gcp-gcr: circleci/gcp-gcr@0.6.1
    gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
version: 2.1
workflows:
    build_and_push_image:
      jobs:
        steps:
            - checkout
            - cloudrun/init
            - cloudrun/build:
                tag: 'gcr.io/ml-webpage-264418/personal-webpage'
            - cloudrun/deploy:
                image: 'gcr.io/ml-webpage-264418/personal-webpage'
                platform: managed
                region: us-east1
                service-name: personal-webpage
                unauthenticated: true
                args:
                    set-env-vars: [aws_secret_access_key=${CIRCLE_BRANCH},aws_access_key_id=${CIRCLE_BRANCH}]
            - run:
                command: >
                    # A simple example of how a deployed managed service could be
                    verified or further tested.
        
                    # This step will send request our "API" and fail if there is
                    unexpected output.
        
                    GCP_API_RESULTS=$(curl -s "$GCP_DEPLOY_ENDPOINT")
                    fi
                name: Test managed deployed service.
