
version: 2.1
orbs:
    gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
jobs:
    build_and_deploy:
        docker:
            - image: 'cimg/base:stable'
        steps:
            - checkout
            - gcp-cloud-run/init
            - gcp-cloud-run/build:
                tag: 'gcr.io/ml-webpage-264418/personal-webpage'
            - gcp-cloud-run/deploy:
                image: 'gcr.io/ml-webpage-264418/personal-webpage'
                platform: managed
                region: europe-west4
                service-name: personal-webpage-circle
                unauthenticated: true
                args: >-
                    --update-env-vars=aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
                    --update-env-vars=aws_access_key_id=${AWS_ACCESS_KEY_ID}
            - run:
                command: >
                    echo --update-env-vars=[aws_secret_access_key=${AWS_SECRET_ACCESS_KEY},aws_access_key_id=${AWS_ACCESS_KEY_ID}]
                    # A simple example of how a deployed managed service could be
                    verified or further tested.

                    # This step will send request our "API" and fail if there is
                    unexpected output.

                    GCP_API_RESULTS=$(curl -s "$GCP_DEPLOY_ENDPOINT")
                    echo $GCP_API_RESULTS
                name: Test managed deployed service.


workflows:
    build_and_deploy_to_managed_workflow:
        jobs:
            - build_and_deploy
