orbs:
    gcp-gcr: circleci/gcp-gcr@0.6.1
version: 2.1
workflows:
    build_and_push_image:
      jobs:
        - gcp-gcr/build-and-push-image:
            image: personal_web
            registry-url: gcr.io
            path: ..
            google-project-id: ml-webpage-264418
            gcloud-service-key: $GCLOUD_SERVICE_KEY
